### ISSUE TITLE
Roadmap for terraform-provider-sonarcloud

### ISSUE THREAD

**Issue by esrahofstede** [rewe-digital/terraform-provider-sonarcloud#15]
Thank you for creating the terraform integration with sonarcloud 😄.
This repository makes it easier to create groups, permissions and users.

What is the future of this repository? 
Is there a roadmap for new functionality to be added?

When looking at the [https://sonarcloud.io/web_api/](https://sonarcloud.io/web_api/) definition, there are many more useful API's. Especially the ones creating and managing projects, project_links and project_tags. 
It would also be nice if you can manage qualitygates, qualityprofiles, rules and settings by terraform.
Will these be added in the future?

I'm really glad you made this repository, because this reduces the manual RBAC administration. This project can shine even more, if the other API's are added, so we can truly do IAC with SonarCloud

**Comment by reinoudk** [comment]
Hi @esrahofstede !

Sorry, I somehow seemed to have missed this issue (probably due to holidays). We don't have a public roadmap yet, but I'll talk to the team to see if we can create a bit more visibility regarding our plans with this provider. I'm currently looking to improve the internal API code generation, so it will be easier to add support for other API endpoints. 

When that has been done, the next item will be to manage API tokens, so it becomes easier to rotate them. Quality gates would then be a good candidate for the next feature. 

Managing the projects themselves using Terraform is something we are not really sure about using ourselves. We want the teams to have control over this and managing this in a central repository that a different team owns creates a bit of friction in the developer experience. Though that should not prevent it from being added to the provider :smile: . When most of the API code is generated, it shouldn't take too much time to add it anyways.

I'll keep you posted when I have some more information about the roadmap.

**Comment by dgteixeira** [comment]
Hey @reinoudk, first of all, take this 🥇(this is pretty cool!)

Is there any update on the possible roadmap for this?

**Comment by reinoudk** [comment]
Hi @dgteixeira, thanks 😊! 

We have no concrete roadmap yet, but now that the API client covers a large part of SonarCloud's Web API, it should be straightforward to add more functionality. Some things might get tricky, as the API is not a regular REST API and some endpoints don't have any _read_ capability, which we need to compare our state with that at SonarCloud. 

Are there any resources / data sources that would be of most importance to you? I plan to release v0.2.0 next week, which should add the `sonarcloud_project` resource and data source.

**Comment by GreggSchofield** [comment]
Hello!

I really like what you have all done here with this terraform provider! I would really like to contribute in any way that I can to increase the surface-area that this provider covers for the SonarCloud API. Does anyone have an idea of a small/medium task I could undertake to dip my toes into the water?

Cheers

**Comment by reinoudk** [comment]
Hi @GreggSchofield, that would be pretty cool :smiley:. I think that adding a data source would a good way to get started, as you'd only need to implement `Read` ([example](https://github.com/rewe-digital/terraform-provider-sonarcloud/blob/main/sonarcloud/data_source_user_group.go)). What about [webhooks](https://sonarcloud.io/web_api/api/webhooks?deprecated=false)? This would be a nice feature to have, as it enables you to build more integrations with SonarCloud.  

You could start by creating a data source to list current webhooks and later on expand on that to also create the resource to actually create / update / delete webhooks. I can of course support if you were to get stuck on anything. What do you think?

**Comment by reinoudk** [comment]
> * Add a data_source_webhooks.go file with data source implementation
> 
> * Add a data_source_webhooks_test.go file with the associated test

Yeah, that's sounds about right. Please note that for executing acceptance tests, you'll need your own test-organization for now, until I've done something about #63.

> * Add a data-source.tf for mock data under a ./examples/data-sources/sonarcloud_webhooks directory?

These examples are used as part of generating the docs so are good to have. You can generate docs using `make docs`, which uses [hashicorp/terraform-plugin-docs](https://github.com/hashicorp/terraform-plugin-docs) under the hood.

> I may need some guidance on how to use/invoke the data_source_webhooks.go from the provider.go file as my understanding breaks down a little here.

It should suffice to add it to the map at [line 100 of provider.go](https://github.com/rewe-digital/terraform-provider-sonarcloud/blob/main/sonarcloud/provider.go#L100). Please let me know if I can help any further.

**Comment by Bhutania** [comment]
Good afternoon @reinoudk,

I was interested in this project so I went ahead and[ forked the repository](https://github.com/Bhutania/terraform-provider-sonarcloud/tree/quality-gates) to implement quality gates. I'm fairly new to go, so I thought I would get your thoughts on what I have implemented. Worst comes to worst, I will have created a scaffolding for someone else to build off of. But hopefully I haven't created too many glaring issues. 😓 

I tried to follow the way that the other resources and data types have been set, but since the Quality Gate is a more complex datatype there were some areas where I had to improvise. 

I would also like to get your thoughts on how to link projects and quality gates.  I was thinking of either:
- Integrating it as a field in the Quality Gates'/Projects' schema.
- Creating a new resource/data type

Do note that I am still working on the resource's Update, Delete, and importState operations.

I haven't been able to run the unit or acceptance tests yet. I'm resolving some issues with my box's root permissions. It does compile 😄 , but that doesn't mean much if the tests fail.

**Comment by reinoudk** [comment]
Very cool @Bhutania! I'll have a closer look this afternoon, but from a first glance it's looking good I think :slightly_smiling_face:. 

The only thing that I might change already is the casing of the attributes. Instead of using camelCase, I'd use snake_case, as this is the [convention](https://www.terraform.io/plugin/sdkv2/best-practices/naming#attribute-names) for attribute names. 

As for linking the two, I think it is a separate resource, and implementing it as such will keep both the code cleaner and the usage more flexible. Not sure if this use-case is a valid one, but if you'd want to use a built-in, non-default quality gate, you wouldn't be able to, unless you have the separate resource to link the two.

**Comment by reinoudk** [comment]
@Bhutania I've created #76 for further discussions. If you want, you can create a (draft) PR so I can support by leaving comments on the code directly

**Comment by reinoudk** [comment]
@GreggSchofield did you by any chance have time yet to look at implementing the webhooks? Anything I can help with? If you don't have the time for it, that's OK too :slightly_smiling_face:; I should have some time this week to implement it in that case.

Note: I've created #77 to further track the webhooks implementation.

**Comment by reinoudk** [comment]
I'm closing this as there are some feature requests open already and we currently have a v0.4.0 and v0.5.0 milestone.
